[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"